---
- name: set repository and cmd path
  set_fact:
    repositories:
      - repo: github.com/x-motemen/ghq
        version: v1.1.5
        cmd: ""
        bin: ghq
      - repo: github.com/peco/peco
        version: v0.5.8
        cmd: cmd/peco
        bin: peco
      - repo: github.com/direnv/direnv
        version: v2.24.0
        cmd: ""
        bin: direnv
      - repo: github.com/cli/cli
        version: v1.3.0
        cmd: cmd/gh
        bin: gh
      - repo: github.com/go-acme/lego
        version: v4.1.3
        cmd: cmd/lego
        bin: lego
      - repo: github.com/golangci/golangci-lint
        version: v1.33.0
        cmd: cmd/golangci-lint
        bin: golangci-lint
      - repo: github.com/golang/tools
        version: gopls/v0.5.3
        cmd: gopls
        bin: gopls
      - repo: github.com/catatsuy/notify_slack
        version: v0.4.7
        cmd: cmd/notify_slack
        bin: notify_slack
      - repo: github.com/cosmtrek/air
        version: v1.15.1
        cmd: ""
        bin: air
      - repo: github.com/schemalex/schemalex
        version: v0.1.1
        cmd: cmd/schemalex
        bin: schemalex
      - repo: github.com/ramya-rao-a/go-outline
        version: master
        cmd: ""
        bin: go-outline

- name: clone tool sources
  git:
    depth: 1
    repo: "https://{{ item.repo }}.git"
    dest: "{{ lookup('env','HOME') }}/src/{{ item.repo }}"
    version: "{{ item.version }}"
    update: no
  with_items: "{{ repositories }}"

- name: check installed
  stat:
    path: "{{ lookup('env','HOME') }}/usr/local/bin/{{ item.bin }}"
  with_items: "{{ repositories }}"
  register: existence

- name: install
  shell:
    cmd: "go install"
    chdir: "{{ lookup('env','HOME') }}/src/{{ item.item.repo }}/{{ item.item.cmd }}"
  environment:
    GOBIN: "{{ lookup('env','HOME') }}/bin"
  when: not item.stat.exists
  with_items: "{{ existence.results }}"
