---

- homebrew:
    state: present
    name:
      - coreutils
      - q
      - jq
      - wget
      - peco
      - packer
      - ag
      - jd
      - percona-toolkit # pt-query-digest
      - emacs
      - ghq
      - direnv
      - gnu-tar
      - protobuf
      - rclone
    #install_options: ""


# - homebrew_cask:
#     state: present
#     name: "{{ item.name }}"
#     install_options: "{{ item.option }}"
#   with_items:
#     - { name: firefox, option: "language=ja" }

- file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ lookup('env','HOME') }}/usr/local/bin/{{ item.command }}"
  with_items:
    - src: /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport
      command: airport
    - src: /usr/local/opt/gnu-tar/libexec/gnubin/tar
      command: tar
